import { Fragment } from 'react';
// next
import Head from 'next/head';
// components
import Profile from '@/components/Profile';
import Skills from '@/components/Skills';
import FeaturedProjects from '@/components/Project/Featured';
// utils
import { getAllProjectsMeta } from '@/utils/project';
// types
import { IProject } from '@/types';

interface Props {
  projects: IProject[];
}

export default function HomePage({ projects }: Props) {
  return (
    <Fragment>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='flex flex-col gap-12'>
        <Profile />
        <Skills />
        <FeaturedProjects projects={projects} />
      </div>
    </Fragment>
  );
}


export async function getStaticProps() {
  return {
    props: {
      projects: getAllProjectsMeta()
    }
  };
};