import Profile from '@/components/Profile';
import Skills from '@/components/Skills';
import Head from 'next/head';
import { Fragment } from 'react';


export default function HomePage() {
  return (
    <Fragment>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='flex flex-col gap-5'>
        <Profile />
        <Skills />
      </div>
    </Fragment>
  );
}
